name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
latest: 'true'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'release-major'
  minor:
    labels:
      - 'release-minor'
  patch:
    labels:
      - 'release-patch'
  default: patch

template: |
  ## Changes

  $CHANGES